server:
  port: 9000
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?serverTimezone=GMT%2B8
    username: root
    password: 111
#spring 整合mybais
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.offcn.pojo
